export const LOGIN_ACTIONS = {
	LOGIN: 'LOGIN'
}

export const PROFILE_ACTIONS = {
	UPDATE_PROFILE: 'UPDATE_PROFILE'
}

export const STATUS_ACTIONS = {
	UPDATE_CHALLENGE: 'UPDATE_CHALLENGE',
	UPDATE_FULL_ACTIVITIES: 'UPDATE_FULL_ACTIVITIES',
	UPDATE_PERSONAL_RANK: 'UPDATE_PERSONAL_RANK',
	UPDATE_RECENT_ACTIVITY: 'UPDATE_RECENT_ACTIVITY',
	UPDATE_TOTAL_RANK: 'UPDATE_TOTAL_RANK'
}
